import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import AppWrapper from "@/context/app-wrapper";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({subsets: ['latin'], weight: ['500','400','600']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <AppWrapper>
      <body className={poppins.className}>
        <Navbar/>
        {children}
      </body>
     </AppWrapper> 
    </html>
  );
}
